#!/bin/bash

# http://tech.naviplus.co.jp/2014/01/09/tmux%E3%81%A7%E8%A4%87%E6%95%B0%E3%82%B5%E3%83%BC%E3%83%90%E3%81%AE%E5%90%8C%E6%99%82%E3%82%AA%E3%83%9A%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3/

while getopts n: OPT ; do
  case $OPT in
    "n")
      SESSION_NAME=$OPTARG
      ;;
  esac
done
shift $((OPTIND - 1))

if [ -n "$SESSION_NAME" ];then
  session=$SESSION_NAME
else
  session=multi-ssh-`date +%s`
fi
window=multi-ssh

### tmuxのセッションを作成
tmux new-session -d -n $window -s $session
 
### 各ホストにsshログイン
# 最初の1台はsshするだけ
h=$(echo $1 | awk -F, '{print $1}')
n=$(echo $1 | awk -F, '{print $2? $2: 1}')
for j in $(seq 1 $n); do
  if [ $j -ne 1 ]; then
    tmux split-window
    tmux select-layout tiled
  fi
  [ -z "$MULTI_SSH_PROXY" ] || tmux send-keys "ssh $MULTI_SSH_PROXY" C-m
  tmux send-keys "ssh $h" C-m
done
shift

# 残りはpaneを作成してからssh
for i in $*;do
  h=$(echo $i | awk -F, '{print $1}')
  n=$(echo $i | awk -F, '{print $2? $2: 1}')
  for j in $(seq 1 $n); do
    tmux split-window
    tmux select-layout tiled
    [ -z "$MULTI_SSH_PROXY" ] || tmux send-keys "ssh $MULTI_SSH_PROXY" C-m
    tmux send-keys "ssh $h" C-m
  done
done

### 最初のpaneを選択状態にする
tmux select-pane -t 0

### paneの同期モードを設定
tmux set-window-option synchronize-panes on

### セッションにアタッチ
tmux attach-session -t $session
